import { PrismaQueryProvider } from '@apps-next/query-adapter';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import Link from 'next/link';
import { viewLoader, viewMutation } from './fastapp/tasks/actions';
import './global.css';
import Head from 'next/head';

import '@picocss/pico/css/pico.classless.min.css';

export const metadata = {
  title: 'Welcome to nextjs',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
        ></link>
      </Head>

      <body>
        <PrismaQueryProvider
          api={{
            viewLoader: viewLoader,
            viewMutation: viewMutation,
          }}
        >
          <div className="p-2">
            <div className="flex gap-2 text-lg border-b">
              <Link href={'/'}>Home</Link>
            </div>

            <hr />

            {children}
          </div>

          <ReactQueryDevtools initialIsOpen={false} />
        </PrismaQueryProvider>
      </body>
    </html>
  );
}
