# name: CI

# on:
#   push:
#     branches:
#       - main
#   pull_request:

# permissions:
#   actions: read
#   contents: read

# jobs:
#   main:
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres
#         env:
#           POSTGRES_PASSWORD: admin
#           POSTGRES_USER: postgres
#           POSTGRES_DB: db
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5
#     env:
#       DATABASE_URL: postgresql://postgres:admin@localhost:5432/db

#     steps:
#       - uses: actions/checkout@v4

#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm ci --force

#       - name: Install Playwright Browser
#         run: npx playwright install

#       - name: Build project
#         run: npx nx build nextjs
#       # - name: Run linter
#       #   run: npm run lint

#       - name: 'Lint and Build Affected...'
#         run: npx nx affected -t lint build

#       - name: Run Playwright tests
#         run: npx nx e2e nextjs-e2e

name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      VITE_CONVEX_URL: https://deafening-marmot-647.convex.cloud
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx nx run apps-next-e2e:e2e-ci
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
