name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: postgres
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:admin@localhost:5432/db

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --force

      - name: Install Playwright Browser
        run: npx playwright install

      - name: Push Prisma schema to database
        run: npx prisma db push

      - name: Build project
        run: npx nx build nextjs
      # - name: Run linter
      #   run: npm run lint

      - name: 'Lint and Build Affected...'
        run: npx nx affected -t lint build

      - name: Run Playwright tests
        run: npx nx e2e nextjs-e2e
